language:  node_js
node_js:
  - "7"

# # Setup for Headless Chrome Testing
# before_script:
#   - npm run dev & 
#   - sleep 30
# script: 
#   - npm run test

# #Install and Use Chrome
# addons:
#   chrome: stable
# dist: trusty
before_deploy:
 - npm run build
 
deploy:
  provider: heroku
  api_key:
    secure: hlHIidJ3gNEQ0I4ZrR5xVoKumgyUliCTNhV2OT8K0SzaY1/kW5q/VIR/GyXpHK9chN3+2eFGONnAknw/VM3PMQWzR+wNWhHDt+K9NMmj+2XpS1RdvkJyo2ovs+7cOPabBc6bW1sGBtnjJ2D5D/quFiVdID66oDG5jFFvv0y4uaspDEvNiVBC9LejjGSr47duF+2pGliYuJEChBGn92SIbu8O5Lmu83SAYQ3NDcdQ1nw29OUKtXX0Q+s292NROpNWN0IhufUuGpWOXJbY5O2W8fkQoF8+/fUU/wXbzVOM47b3LeC+uMqM6ucYLO1WNO5oQUTOAJKoXK2fjDraewZ7Iz37/2DAiUHdWNezmy8orYCGIaYrIkVNrhRazX4pwU0vHR1D1navso89rMPmizorA1KvAknDEicPM7s+j3/4F11Zi42Ex2jDu33JqYra0T55ws0mzZrckn6dzqk8KvkryffN9j5BQg3TGtEYPvM4AqA6dT/mYu5ECVh3Bs3zLh/QXfQYJjOiAU622xp8xMA4z8r+6aVwERfK9vjcnv3fmUsW2MBNfMxhtrosOesOkrpoHui8pYG7/1e1jyAbecnLKARaJegPjyhFJrMVv58VYWuY+QFNbCCZPJx9gvp9RPoHF+Ms6cofu25jrmTaI7oTgdb7r+xxZ6dR2SCwW+wzLRg=
  app: scriptum
  skip_cleanup: true
